export const electronicsData = [
    {
        _id: 21,
        price: 1382,
        rating: 4.5,
        title: 'Apple MacBook Air with M2 Chip',
        image: 'https://m.media-amazon.com/images/I/31t8zcyvapL._SY445_SX342_QL70_FMwebp_.jpg',
        description:
            'Apple MacBook Air (M2, 2022) is a macOS laptop with a 13.60-inch display. It is powered by a Apple M2 processor and it comes with 8GB of RAM. The Apple MacBook Air (M2, 2022) packs 512GB of SSD storage.',
        quantity: 1,
        categoryAll: 'all',
        category: 'electronics',
    },
    {
        _id: 22,
        price: 1201,
        rating: 4.5,
        title: 'Apple MacBook Air Laptop M1 chip',
        image: 'https://m.media-amazon.com/images/I/316ArzLeJ2L._SY445_SX342_QL70_FMwebp_.jpg',
        description:
            'Apple MacBook Air (M1, 2020) is a macOS laptop with a 13.30-inch display that has a resolution of 2560x1600 pixels. It is powered by a Apple M1 processor and it comes with 8GB of RAM. The Apple MacBook Air (M1, 2020) packs 512GB of SSD storage.Connectivity options include Wi-Fi 802.11 a/b/g/n/ac/ax, Bluetooth and it comes with 2 USB ports (2 x Thunderbolt 3 (Type C)), Headphone and Mic Combo Jack ports.',
        quantity: 1,
        categoryAll: 'all',
        category: 'electronics',
    },
    {
        _id: 23,
        price: 1563,
        rating: 4.5,
        title: 'iMac 24 inch Pink',
        image: 'https://www.futureworldindia.in/image/cache/catalog/FWI/mac/iMac%2024/pink%201-416x416.jpg',
        description:
            'The 24-inch iMac has a 4.5K Retina display, an M1 chip, and an 11.5 mm thin aluminum design. It also has 8GB of RAM, 256GB of storage, 2 Thunderbolt 4 ports, 2 USB 3 ports, An Ethernet port, A Magic Keyboard with Touch ID support,A studio-quality three-mic array, A six-speaker sound system, Wi-Fi 6 (802.11ax),Bluetooth 5.0, A user-facing 1080p webcam',
        quantity: 1,
        categoryAll: 'all',
        category: 'electronics',
    },
    {
        _id: 24,
        price: 599,
        rating: 4.5,
        title: 'Mac mini',
        image: 'https://m.media-amazon.com/images/I/61jup8h--XL._SX679_.jpg',
        description:
            "The Mac mini is a small desktop computer made by Apple. It's one of four current Mac desktop computers, positioned between the consumer all-in-one iMac and the professional Mac Studio and Mac Pro.The Mac mini is 7.7 inches (19.7 centimeters), square and 1.4 inches (3.6 centimeters) high, Made of aluminum , Shipped without a screen, keyboard, or mouse, Has a small speaker for basic sounds, but no microphones or cameras,Has a power button on the back",
        quantity: 1,
        categoryAll: 'all',
        category: 'electronics',
    },
    {
        _id: 25,
        price: 8781,
        rating: 4.5,
        title: 'Mac Pro',
        image: 'https://www.bechtle.com/dam/jcr:e7ab49dd-fcc1-48ea-9ea3-7a0829205a8b/mac-pro-ansichten2.png',
        description:
            'Apple MacBook Pro is a macOS laptop with a 13.30-inch display that has a resolution of 2560x1600 pixels. It is powered by a Core i5 processor and it comes with 12GB of RAM. The Apple MacBook Pro packs 512GB of SSD storage.',
        quantity: 1,
        categoryAll: 'all',
        category: 'electronics',
    },
    {
        _id: 26,
        price: 1563,
        rating: 4.5,
        title: 'Apple iPhone 14 Pro',
        image: 'https://m.media-amazon.com/images/I/31GmCJTD0GL._SY445_SX342_QL70_FMwebp_.jpg',
        description:
            "The Apple iPhone 14 Pro was released on September 16, 2022.It has a 48MP main camera, Dynamic Island, and all-day battery.It's available in four colors:Gold, Silver, Space Black, Deep Purple.The base model has 6 GB of RAM and 128 GB of internal storage",
        quantity: 1,
        categoryAll: 'all',
        category: 'electronics',
    },
    {
        _id: 27,
        price: 1199,
        rating: 4.5,
        title: 'Apple iPhone 15 Pro Max',
        image: 'https://m.media-amazon.com/images/I/41JrUCWNjHL._SX300_SY300_QL70_FMwebp_.jpg',
        description:
            'The iPhone 15 Pro Max has the following features:, Display: 6.7-inch OLED touchscreen with a 120 Hz refresh rate and 2796 x 1290 pixel resolution, Processor: Apple A17 Pro hexa-core processor ,RAM: 8 GB, Storage: 128, 256, 512, or 1 TB, Cameras: 12 MP front camera, 48 MP + 12 MP + 12 MP primary camera, Battery: 29 hours of video playback, 95 hours of audio playback, Operating system: iOS 17,Colors: Black Titanium, White Titanium, Blue Titanium, and Natural Titanium, Other features: 5x optical telephoto lens, USB-C with speeds up to 10 Gps, Wi-Fi 6E for up to two times faster wireless speeds',
        quantity: 1,
        categoryAll: 'all',
        category: 'electronics',
    },
    {
        _id: 28,
        price: 1081,
        rating: 4.5,
        title: 'Apple Watch Ultra 2',
        image: 'https://m.media-amazon.com/images/I/51SIYOIWgnL._SY445_SX342_QL70_FMwebp_.jpg',
        description:
            'The most rugged and capable Apple Watch pushes the limits again. Featuring the all-new S9 SiP. A magical new way to use your watch without touching the screen. The brightest Apple display ever. And now you can choose a case and strap combination that is carbon neutral.',
        quantity: 1,
        categoryAll: 'all',
        category: 'electronics',
    },
    {
        _id: 29,
        price: 540,
        rating: 4.5,
        title: 'Apple Watch Series 9',
        image: 'https://m.media-amazon.com/images/I/41SY6xY5hkL._SY445_SX342_QL70_FMwebp_.jpg',
        description:
            'Apple Watch Series 9 also has a new 4-core Neural Engine that can process machine learning tasks up to twice as fast, when compared with Apple Watch Series 8. The power efficiency of the S9 SiP allows Apple Watch Series 9 to maintain all-day 18-hour battery life',
        quantity: 1,
        categoryAll: 'all',
        category: 'electronics',
    },
    {
        _id: 30,
        price: 721,
        rating: 4.5,
        title: 'AirPods Max',
        image: 'https://rukminim2.flixcart.com/image/416/416/kigbjbk0-0/headphone/1/w/h/mgym3hn-a-apple-original-imafy8wc5tej8szy.jpeg?q=70',
        description:
            'From cushion to canopy, AirPods Max are designed for an uncompromising fit that creates the optimal acoustic seal for many different head shapes — fully immersing you in every sound. The canopy spanning the headband is made from a breathable knit mesh, distributing weight to reduce on-head pressure.',
        quantity: 1,
        categoryAll: 'all',
        category: 'electronics',
    },
];

export const productData = [
    {
        _id: 1,
        title: 'Long sleeve Jacket',
        isNew: true,
        oldPrice: '200',
        price: 150,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/41L4Eaht0zL.jpg',
        rating: 4,
        quantity: 1,
    },
    {
        _id: 2,
        title: 'Jacket with wollen hat',
        isNew: true,
        oldPrice: '70',
        price: 65,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/71fpHGiDxrL._UY741_.jpg',
        rating: 3,
        quantity: 1,
    },
    {
        _id: 3,
        title: 'Compact fashion t-shirt',
        isNew: true,
        oldPrice: '70',
        price: 55.99,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/41Zf1+rmL0L._UX679_.jpg',
        rating: 3,
        quantity: 1,
    },
    {
        _id: 4,
        title: 'Blue jeans',
        isNew: true,
        oldPrice: '70',
        price: 50,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/61kBiRSFWgL._UY879_.jpg',
        rating: 3,
        quantity: 1,
    },
    {
        _id: 5,
        title: 'Skirts with full setup',
        isNew: true,
        oldPrice: '800',
        price: 695,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/610sSMZDBDL._UX679_.jpg',
        rating: 5,
        quantity: 1,
    },
    {
        _id: 6,
        title: 'Yellow Hoody',
        isNew: false,
        oldPrice: '200',
        price: 180,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'men',
        image: 'https://m.media-amazon.com/images/I/71HLzkQvV-L._UX679_.jpg',
        rating: 4,
        quantity: 1,
    },
    {
        _id: 7,
        title: 'Black t-shirt for women',
        isNew: false,
        oldPrice: '60',
        price: 20,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/51VHATON2UL._UY879_.jpg',
        rating: 2,
        quantity: 1,
    },
    {
        _id: 8,
        title: 'Gouwn with Red velvet',
        isNew: false,
        oldPrice: '500',
        price: 350,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/51FaghMJAQL._UX679_.jpg',
        rating: 3,
        quantity: 1,
    },
    {
        _id: 9,
        title: "Dream Beauty Fashion Women's V-Neck Full Sleeve Crop Top Baati",
        isNew: false,
        oldPrice: '150',
        price: 100,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/61TqPSaoFiL._UY741_.jpg',
        rating: 3,
        quantity: 1,
    },
    {
        _id: 10,
        title: "Jean's stylish Jacket",
        isNew: false,
        oldPrice: '250',
        price: 245,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'men',
        image: 'https://m.media-amazon.com/images/I/61G1ZLzdBeS._UX679_.jpg',
        rating: 5,
        quantity: 1,
    },
    {
        _id: 11,
        title: 'Round neck t-shirt',
        isNew: false,
        oldPrice: '1000',
        price: 800,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/51jv4aO1hkL._UY741_.jpg',
        rating: 4,
        quantity: 1,
    },
    {
        _id: 12,
        title: 'Black Jacket',
        isNew: false,
        oldPrice: '200',
        price: 140,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'men',
        image: 'https://m.media-amazon.com/images/I/61D2ou4BoaL._UY879_.jpg',
        rating: 3,
        quantity: 1,
    },
    {
        _id: 13,
        title: 'Black top with jeans',
        isNew: false,
        oldPrice: '130',
        price: 120,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/51u9oc1gDlL._UX679_.jpg',
        rating: 4,
        quantity: 1,
    },
    {
        _id: 14,
        title: "Mother's Choice Baby Boys' Clothing Set",
        isNew: false,
        oldPrice: '80',
        price: 50,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'kids',
        image: 'https://m.media-amazon.com/images/I/81N-Es0RPmL._UY741_.jpg',
        rating: 2,
        quantity: 1,
    },
    {
        _id: 15,
        title: "jannon Women's Solid Stretchable High Waist Slim Fit Jeans",
        isNew: false,
        oldPrice: '120',
        price: 100,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/61x+w7lNNtL._UX679_.jpg',
        rating: 4,
        quantity: 1,
    },
    {
        _id: 16,
        title: "Aradhana Fashion Women's Engrossing Readymade Cotton Nauvari Saree",
        isNew: false,
        oldPrice: '400',
        price: 350,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/71MltIpH47L._UY879_.jpg',
        rating: 4,
        quantity: 1,
    },
    {
        _id: 17,
        title: 'Light tops',
        isNew: false,
        oldPrice: '140',
        price: 120,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/61Gc4lqignL._UY741_.jpg',
        rating: 3,
        quantity: 1,
    },
    {
        _id: 18,
        title: 'Khakhi jeans',
        isNew: false,
        oldPrice: '250',
        price: 190,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/61Te9UNzSxL._UY741_.jpg',
        rating: 4,
        quantity: 1,
    },
    {
        _id: 19,
        title: 'Black full sleeve',
        isNew: false,
        oldPrice: '180',
        price: 170,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'women',
        image: 'https://m.media-amazon.com/images/I/518aR0Pb13L._UY879_.jpg',
        rating: 3,
        quantity: 1,
    },
    {
        _id: 20,
        title: 'Formal for Men',
        isNew: false,
        oldPrice: '500',
        price: 490,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla non magni facili blanditiis molestias soluta eveniet illum accusantium eius mollitia eligendi, ex iste doloribus magnam.',
        categoryAll: 'all',
            category: 'men',
        image: 'https://m.media-amazon.com/images/I/71Jwe2kb5pL._UY879_.jpg',
        rating: 5,
        quantity: 1,
    },
];

export const combinedData = [...productData, ...electronicsData];
