import './globals.css';
import { Roboto } from 'next/font/google';
import StoreProvider from './provider/StoreProvider';
import PersistorProvider from './provider/PersistorProvider';
import Header from './components/Header';
import Footer from './components/Footer';
const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
    display: 'swap'
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
    return (
        <StoreProvider>
            <html lang='en'>
                <body className={`${roboto.className} bg-white antialiased`}>
                    <Header />
                    <PersistorProvider>{children}</PersistorProvider>
                    <Footer />
                </body>
            </html>
        </StoreProvider>
    );
}
